version: "3"
services:
  app:
    container_name: app
    build: ./config/php
    volumes:
      - .:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8090:80
    volumes:
      - .:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  mysql:
    # MySQL公式が用意しているDockerイメージ 8.0.30
    # https://gihyo.jp/dev/serial/01/mysql-road-construction-news/0167
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api-user
      MYSQL_PASSWORD: corasp@pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./config/db/data:/var/lib/mysql
      - ./config/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./config/db/sql:/config-entrypoint-initdb.d
    ports:
      - 18080:3306